site_name: Test Site
theme:
  name: material
  palette:
    primary: custom
    accent: green

nav:
  - Home: index.md
  - Test Folder:
    - Topic One: test-folder/topic1.md
    - Topic Two: test-folder/topic2.md
